services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./ollama/storage:/root/.ollama
    ports:
      - ${OLLAMA_PORT}:11434
  chroma:
    image: chromadb/chroma
    container_name: chroma
    volumes:
      - ./chroma/storage:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - ${CHROMA_PORT}:8000
  rag_api:
    container_name: rag-api
    build:
      context: ./rag-api
      dockerfile: Dockerfile.${BUILD_TARGET}
    ports:
      - ${RAG_API_PORT}:80
    volumes:
      - ./rag-api:/app/
      - ./rag-api/storage:/app/storage
    environment:
      - BUILD_TARGET=${BUILD_TARGET}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - CHROMA_PORT=${CHROMA_PORT}
      - RAG_API_PORT=${RAG_API_PORT}