services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./ollama/storage:/root/.ollama
    ports:
      - ${OLLAMA_PORT}:11434
  chroma:
    image: chromadb/chroma
    container_name: chroma
    volumes:
      - ./chroma/storage:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - ${CHROMA_PORT}:8000
  milvus:
    image: milvusdb/milvus:v2.4.1
    container_name: milvus
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - "${MILVUS_PORT}:19530"
      - "9091:9091"
      - "2379:2379"
    volumes:
      - ./milvus/storage:/var/lib/milvus
      - type: bind
        source: ./milvus/embedEtcd.yaml
        target: /milvus/configs/embedEtcd.yaml
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    command: ["milvus", "run", "standalone"]
  rag_api:
    container_name: rag-api
    build:
      context: ./rag-api
      dockerfile: Dockerfile.${BUILD_TARGET}
    ports:
      - ${RAG_API_PORT}:80
    volumes:
      - ./rag-api:/app/
      - ./rag-api/storage:/app/storage
    environment:
      - BUILD_TARGET=${BUILD_TARGET}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - CHROMA_PORT=${CHROMA_PORT}
      - MILVUS_PORT=${MILVUS_PORT}
      - RAG_API_PORT=${RAG_API_PORT}